### ISSUE TITLE
Support conditional arrays

### ISSUE THREAD

**Issue by stephenlacy** [contra/jif#2]
Would be nice to do this:

```js
jif(isTrue, [renderFirst, renderSecond, renderThird])
```
The array could accept only functions, or any value as it currently does.

**Comment by yocontra** [comment]
@stevelacy Should be pretty easy to resolve functions in https://github.com/contra/jif/blob/master/src/index.js#L1

**Comment by stephenlacy** [comment]
Sounds good, I'll send a PR when I get to it
